// AUTO-GENERATED by scripts/gen-migrations.mjs — do not edit by hand.
export default {
  "journal": {
    "version": "7",
    "dialect": "sqlite",
    "entries": [
      {
        "idx": 0,
        "version": "6",
        "when": 1790284620263,
        "tag": "0000_material_mac_gargan",
        "breakpoints": true
      }
    ]
  },
  "migrations": {
    "m0000": "CREATE TABLE `cache_entries` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n"
  }
};
