import '../models/achievement.dart';

/// Third-wave catalog seeds (v3 milestones).
const List<Achievement> bulkAchievementSeedsV3 = [
  Achievement(
    id: 'edu-seed-v3-latin-honors',
    category: AchievementCategory.education,
    title: 'Latin Honors',
    description: 'Graduated with cum laude or higher',
    xpValue: 35,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-community-college',
    category: AchievementCategory.education,
    title: 'Community College',
    description: 'Earned an associate degree',
    xpValue: 47,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-ged',
    category: AchievementCategory.education,
    title: 'GED Complete',
    description: 'Earned high school equivalency',
    xpValue: 59,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-sat-perfect',
    category: AchievementCategory.education,
    title: 'Perfect Section',
    description: 'Scored perfect on a major exam section',
    xpValue: 71,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-physics-olympiad',
    category: AchievementCategory.education,
    title: 'Physics Medal',
    description: 'Medaled in physics olympiad',
    xpValue: 83,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-chemistry-lab',
    category: AchievementCategory.education,
    title: 'Chem Lab Lead',
    description: 'Led a university chemistry lab section',
    xpValue: 95,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-history-paper',
    category: AchievementCategory.education,
    title: 'History Prize Paper',
    description: 'Won a history department paper prize',
    xpValue: 107,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-statistics-minor',
    category: AchievementCategory.education,
    title: 'Statistics Minor',
    description: 'Completed a statistics minor',
    xpValue: 119,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-philosophy-thesis',
    category: AchievementCategory.education,
    title: 'Philosophy Thesis',
    description: 'Defended a philosophy thesis',
    xpValue: 131,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-library-thesis',
    category: AchievementCategory.education,
    title: 'Archival Research',
    description: 'Completed archival thesis research',
    xpValue: 143,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-peer-review',
    category: AchievementCategory.education,
    title: 'Peer Reviewer',
    description: 'Peer-reviewed journal submissions',
    xpValue: 155,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-teaching-assistant',
    category: AchievementCategory.education,
    title: 'Teaching Assistant',
    description: 'TA\'d a core course for a year',
    xpValue: 167,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-audit-course',
    category: AchievementCategory.education,
    title: 'Audit Scholar',
    description: 'Audited a university course for enrichment',
    xpValue: 179,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-coding-bootcamp-teach',
    category: AchievementCategory.education,
    title: 'Bootcamp Mentor',
    description: 'Mentored bootcamp cohort',
    xpValue: 191,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'edu-seed-v3-grad-school-offer',
    category: AchievementCategory.education,
    title: 'Grad School Offer',
    description: 'Received a grad school offer',
    xpValue: 203,
    icon: 'history_edu',
  ),
  Achievement(
    id: 'car-seed-v3-four-day',
    category: AchievementCategory.career,
    title: 'Four-Day Week',
    description: 'Worked a four-day week policy a year',
    xpValue: 35,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-parental-leave',
    category: AchievementCategory.career,
    title: 'Parental Return',
    description: 'Returned from parental leave successfully',
    xpValue: 47,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-whistleblower',
    category: AchievementCategory.career,
    title: 'Ethics Reporter',
    description: 'Reported ethics issue through proper channels',
    xpValue: 59,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-union-organize',
    category: AchievementCategory.career,
    title: 'Union Organizer',
    description: 'Helped organize a workplace union drive',
    xpValue: 71,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-acquisition',
    category: AchievementCategory.career,
    title: 'Acquisition Survivor',
    description: 'Stayed through an acquisition integration',
    xpValue: 83,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-layoff-support',
    category: AchievementCategory.career,
    title: 'Layoff Support',
    description: 'Supported teammates through layoffs',
    xpValue: 95,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-customer-save',
    category: AchievementCategory.career,
    title: 'Customer Save',
    description: 'Saved a major customer relationship',
    xpValue: 107,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-zero-incident',
    category: AchievementCategory.career,
    title: 'Zero Incident Quarter',
    description: 'Team had zero safety incidents a quarter',
    xpValue: 119,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-innovation-award',
    category: AchievementCategory.career,
    title: 'Innovation Award',
    description: 'Won a company innovation award',
    xpValue: 131,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-cross-team',
    category: AchievementCategory.career,
    title: 'Cross Team Lead',
    description: 'Led a cross-functional initiative',
    xpValue: 143,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-mentor-program',
    category: AchievementCategory.career,
    title: 'Mentor Program Lead',
    description: 'Ran a formal mentorship program',
    xpValue: 155,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-exit-founder',
    category: AchievementCategory.career,
    title: 'Founder Exit',
    description: 'Exited a company you founded',
    xpValue: 167,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-performance-review',
    category: AchievementCategory.career,
    title: 'Top Review',
    description: 'Earned top performance review rating',
    xpValue: 179,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-salary-transparency',
    category: AchievementCategory.career,
    title: 'Pay Transparency',
    description: 'Advocated pay transparency successfully',
    xpValue: 191,
    icon: 'home_work',
  ),
  Achievement(
    id: 'car-seed-v3-contract-negotiate',
    category: AchievementCategory.career,
    title: 'Contract Win',
    description: 'Negotiated a strong contract',
    xpValue: 203,
    icon: 'home_work',
  ),
  Achievement(
    id: 'rel-seed-v3-double-date',
    category: AchievementCategory.relationships,
    title: 'Double Date',
    description: 'Went on a double date that actually worked',
    xpValue: 35,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-v3-apology-letter',
    category: AchievementCategory.relationships,
    title: 'Apology Letter',
    description: 'Wrote a meaningful apology letter',
    xpValue: 47,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-v3-family-recipe',
    category: AchievementCategory.relationships,
    title: 'Family Recipe',
    description: 'Learned a family recipe from an elder',
    xpValue: 59,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-v3-sibling-trip',
    category: AchievementCategory.relationships,
    title: 'Sibling Trip',
    description: 'Traveled with a sibling',
    xpValue: 71,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-v3-neighbor-dinner',
    category: AchievementCategory.relationships,
    title: 'Neighbor Dinner',
    description: 'Hosted neighbors for dinner',
    xpValue: 83,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-v3-friend-therapy',
    category: AchievementCategory.relationships,
    title: 'Friend Support',
    description: 'Supported a friend through crisis',
    xpValue: 95,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-v3-pet-loss',
    category: AchievementCategory.relationships,
    title: 'Pet Memorial',
    description: 'Held memorial for a beloved pet',
    xpValue: 107,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-v3-long-friendship',
    category: AchievementCategory.relationships,
    title: 'Twenty Year Friend',
    description: 'Friendship lasted twenty years',
    xpValue: 119,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-v3-mentor-family',
    category: AchievementCategory.relationships,
    title: 'Family Mentor',
    description: 'Mentored a younger family member',
    xpValue: 131,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-v3-community-parent',
    category: AchievementCategory.relationships,
    title: 'Community Parent',
    description: 'Parented with community support',
    xpValue: 143,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-v3-engagement-party',
    category: AchievementCategory.relationships,
    title: 'Engagement Party',
    description: 'Hosted an engagement celebration',
    xpValue: 155,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-v3-friend-roadtrip',
    category: AchievementCategory.relationships,
    title: 'Friends Road Trip',
    description: 'Road-tripped with close friends',
    xpValue: 167,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-v3-family-game-night',
    category: AchievementCategory.relationships,
    title: 'Family Game Night',
    description: 'Ran monthly family game nights',
    xpValue: 179,
    icon: 'favorite',
  ),
  Achievement(
    id: 'hlth-seed-v3-75-hard',
    category: AchievementCategory.health,
    title: '75 Hard',
    description: 'Completed 75 Hard or equivalent challenge',
    xpValue: 35,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-ruck-march',
    category: AchievementCategory.health,
    title: 'Ruck March',
    description: 'Finished a weighted ruck event',
    xpValue: 47,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-swim-mile',
    category: AchievementCategory.health,
    title: 'Mile Swim',
    description: 'Swam a continuous mile',
    xpValue: 59,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-handstand',
    category: AchievementCategory.health,
    title: 'Handstand Hold',
    description: 'Held a handstand thirty seconds',
    xpValue: 71,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-flexibility',
    category: AchievementCategory.health,
    title: 'Splits Progress',
    description: 'Reached a flexibility milestone',
    xpValue: 83,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-sleep-8',
    category: AchievementCategory.health,
    title: 'Eight Hour Month',
    description: 'Slept eight hours average a month',
    xpValue: 95,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-no-caffeine',
    category: AchievementCategory.health,
    title: 'Caffeine Break',
    description: 'Skipped caffeine thirty days',
    xpValue: 107,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-plant-based',
    category: AchievementCategory.health,
    title: 'Plant Based Quarter',
    description: 'Ate plant-based ninety days',
    xpValue: 119,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-pt-complete',
    category: AchievementCategory.health,
    title: 'PT Graduate',
    description: 'Graduated physical therapy program',
    xpValue: 131,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-ergonomic',
    category: AchievementCategory.health,
    title: 'Ergonomic Setup',
    description: 'Built an ergonomic desk setup',
    xpValue: 143,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-flu-shot',
    category: AchievementCategory.health,
    title: 'Flu Season Ready',
    description: 'Got flu shot two years running',
    xpValue: 155,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-walk-10k-daily',
    category: AchievementCategory.health,
    title: 'Walk Streak',
    description: 'Walked ten thousand steps sixty days',
    xpValue: 167,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-blood-pressure',
    category: AchievementCategory.health,
    title: 'BP Track',
    description: 'Tracked blood pressure twelve weeks',
    xpValue: 179,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-cholesterol-down',
    category: AchievementCategory.health,
    title: 'Cholesterol Win',
    description: 'Improved cholesterol with lifestyle',
    xpValue: 191,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'hlth-seed-v3-posture-desk',
    category: AchievementCategory.health,
    title: 'Desk Posture',
    description: 'Fixed desk posture for ninety days',
    xpValue: 203,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'skl-seed-v3-rust-ship',
    category: AchievementCategory.skills,
    title: 'Rust Ship',
    description: 'Shipped a Rust project to production',
    xpValue: 35,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-flutter-ship',
    category: AchievementCategory.skills,
    title: 'Flutter Ship',
    description: 'Published a Flutter app',
    xpValue: 47,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-arduino',
    category: AchievementCategory.skills,
    title: 'Arduino Build',
    description: 'Built a working Arduino project',
    xpValue: 59,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-hydroponics',
    category: AchievementCategory.skills,
    title: 'Hydroponics',
    description: 'Ran a hydroponic grow cycle',
    xpValue: 71,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-knitting',
    category: AchievementCategory.skills,
    title: 'Knitting Gift',
    description: 'Knitted gifts for five people',
    xpValue: 83,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-leathercraft',
    category: AchievementCategory.skills,
    title: 'Leather Craft',
    description: 'Made a leather goods piece',
    xpValue: 95,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-glassblowing',
    category: AchievementCategory.skills,
    title: 'Glass Piece',
    description: 'Created a glass art piece',
    xpValue: 107,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-magic-trick',
    category: AchievementCategory.skills,
    title: 'Magic Repertoire',
    description: 'Performed ten magic tricks live',
    xpValue: 119,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-juggling',
    category: AchievementCategory.skills,
    title: 'Juggling Five',
    description: 'Juggled five balls consistently',
    xpValue: 131,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-speedcube',
    category: AchievementCategory.skills,
    title: 'Cube Sub-60',
    description: 'Solved Rubik cube under sixty seconds',
    xpValue: 143,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-home-lab',
    category: AchievementCategory.skills,
    title: 'Home Lab',
    description: 'Ran a homelab server a year',
    xpValue: 155,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-ham-repeat',
    category: AchievementCategory.skills,
    title: 'Ham Contact',
    description: 'Made fifty ham radio contacts',
    xpValue: 167,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-drone-license',
    category: AchievementCategory.skills,
    title: 'Drone Pilot',
    description: 'Earned Part 107 or equivalent drone license',
    xpValue: 179,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-soldering',
    category: AchievementCategory.skills,
    title: 'Solder Pro',
    description: 'Soldered complex electronics board',
    xpValue: 191,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-v3-cnc-part',
    category: AchievementCategory.skills,
    title: 'CNC Part',
    description: 'Machined a part on CNC',
    xpValue: 203,
    icon: 'code',
  ),
  Achievement(
    id: 'trv-seed-v3-biome-3',
    category: AchievementCategory.travel,
    title: 'Three Biomes',
    description: 'Visited three biomes one trip',
    xpValue: 60,
    icon: 'hiking',
  ),
  Achievement(
    id: 'trv-seed-v3-canyon',
    category: AchievementCategory.travel,
    title: 'Canyon Hike',
    description: 'Hiked a major canyon',
    xpValue: 72,
    icon: 'hiking',
  ),
  Achievement(
    id: 'trv-seed-v3-volcano',
    category: AchievementCategory.travel,
    title: 'Volcano View',
    description: 'Viewed an active volcano safely',
    xpValue: 84,
    icon: 'hiking',
  ),
  Achievement(
    id: 'trv-seed-v3-glacier',
    category: AchievementCategory.travel,
    title: 'Glacier Trek',
    description: 'Trekked near a glacier',
    xpValue: 96,
    icon: 'hiking',
  ),
  Achievement(
    id: 'trv-seed-v3-safari',
    category: AchievementCategory.travel,
    title: 'Safari Day',
    description: 'Completed a safari day trip',
    xpValue: 108,
    icon: 'hiking',
  ),
  Achievement(
    id: 'trv-seed-v3-metro-10',
    category: AchievementCategory.travel,
    title: 'Ten Metros',
    description: 'Rode metros in ten cities',
    xpValue: 120,
    icon: 'hiking',
  ),
  Achievement(
    id: 'trv-seed-v3-bike-tour',
    category: AchievementCategory.travel,
    title: 'Bike Tour',
    description: 'Bike-toured a region',
    xpValue: 132,
    icon: 'hiking',
  ),
  Achievement(
    id: 'trv-seed-v3-couch-surf',
    category: AchievementCategory.travel,
    title: 'Couch Surf',
    description: 'Couch-surfed five cities ethically',
    xpValue: 144,
    icon: 'hiking',
  ),
  Achievement(
    id: 'trv-seed-v3-border-walk',
    category: AchievementCategory.travel,
    title: 'Border Town',
    description: 'Visited a border town thoughtfully',
    xpValue: 156,
    icon: 'hiking',
  ),
  Achievement(
    id: 'trv-seed-v3-lighthouse',
    category: AchievementCategory.travel,
    title: 'Lighthouse',
    description: 'Visited five lighthouses',
    xpValue: 168,
    icon: 'hiking',
  ),
  Achievement(
    id: 'trv-seed-v3-overnight-train',
    category: AchievementCategory.travel,
    title: 'Sleeper Train',
    description: 'Slept on an overnight train',
    xpValue: 180,
    icon: 'hiking',
  ),
  Achievement(
    id: 'trv-seed-v3-cave-tour',
    category: AchievementCategory.travel,
    title: 'Cave Tour',
    description: 'Toured a show cave or wild cave safely',
    xpValue: 192,
    icon: 'hiking',
  ),
  Achievement(
    id: 'trv-seed-v3-thermal-spring',
    category: AchievementCategory.travel,
    title: 'Hot Spring',
    description: 'Visited a thermal spring',
    xpValue: 204,
    icon: 'hiking',
  ),
  Achievement(
    id: 'fin-seed-v3-credit-freeze',
    category: AchievementCategory.finance,
    title: 'Fraud Freeze',
    description: 'Reacted quickly to fraud with freezes',
    xpValue: 60,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'fin-seed-v3-split-bills',
    category: AchievementCategory.finance,
    title: 'Split Bills Pro',
    description: 'Split shared bills fairly a year',
    xpValue: 72,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'fin-seed-v3-coupon-master',
    category: AchievementCategory.finance,
    title: 'Coupon Master',
    description: 'Saved meaningfully with intentional coupons',
    xpValue: 84,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'fin-seed-v3-side-hustle-profit',
    category: AchievementCategory.finance,
    title: 'Side Profit',
    description: 'Side hustle profitable six months',
    xpValue: 96,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'fin-seed-v3-student-loan',
    category: AchievementCategory.finance,
    title: 'Student Loan Plan',
    description: 'Executed a student loan payoff plan',
    xpValue: 108,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'fin-seed-v3-mortgage-pay',
    category: AchievementCategory.finance,
    title: 'Mortgage Extra',
    description: 'Paid extra mortgage principal a year',
    xpValue: 120,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'fin-seed-v3-dividend-income',
    category: AchievementCategory.finance,
    title: 'Dividend Track',
    description: 'Tracked dividend income quarterly',
    xpValue: 132,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'fin-seed-v3-crypto-tax',
    category: AchievementCategory.finance,
    title: 'Crypto Taxes',
    description: 'Filed crypto taxes accurately',
    xpValue: 144,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'fin-seed-v3-financial-advisor',
    category: AchievementCategory.finance,
    title: 'Advisor Meet',
    description: 'Met a fiduciary advisor',
    xpValue: 156,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'fin-seed-v3-kids-allowance',
    category: AchievementCategory.finance,
    title: 'Allowance System',
    description: 'Ran an allowance teaching system',
    xpValue: 168,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'fin-seed-v3-emergency-3mo',
    category: AchievementCategory.finance,
    title: 'Three Month Fund',
    description: 'Built three month emergency fund',
    xpValue: 180,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'fin-seed-v3-credit-builder',
    category: AchievementCategory.finance,
    title: 'Credit Builder',
    description: 'Used secured card to build credit',
    xpValue: 192,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'fin-seed-v3-expense-track',
    category: AchievementCategory.finance,
    title: 'Expense Track',
    description: 'Tracked every expense ninety days',
    xpValue: 204,
    icon: 'account_balance',
  ),
  Achievement(
    id: 'com-seed-v3-bike-repair',
    category: AchievementCategory.community,
    title: 'Bike Repair Clinic',
    description: 'Volunteered at bike repair clinic',
    xpValue: 35,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'com-seed-v3-meal-train',
    category: AchievementCategory.community,
    title: 'Meal Train',
    description: 'Organized a meal train',
    xpValue: 47,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'com-seed-v3-scholarship-fund',
    category: AchievementCategory.community,
    title: 'Micro Scholarship',
    description: 'Funded a micro scholarship',
    xpValue: 59,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'com-seed-v3-poll-worker',
    category: AchievementCategory.community,
    title: 'Poll Worker',
    description: 'Worked as election poll worker',
    xpValue: 71,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'com-seed-v3-translator-vol',
    category: AchievementCategory.community,
    title: 'Translator Volunteer',
    description: 'Translated for community events',
    xpValue: 83,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'com-seed-v3-habitat-lead',
    category: AchievementCategory.community,
    title: 'Habitat Lead',
    description: 'Led a habitat build day',
    xpValue: 95,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'com-seed-v3-park-bench',
    category: AchievementCategory.community,
    title: 'Bench Sponsor',
    description: 'Sponsored a park bench or tree',
    xpValue: 107,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'com-seed-v3-little-library',
    category: AchievementCategory.community,
    title: 'Little Library',
    description: 'Installed a little free library',
    xpValue: 119,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'com-seed-v3-neighbor-shovel',
    category: AchievementCategory.community,
    title: 'Snow Neighbor',
    description: 'Shoveled neighbors driveways',
    xpValue: 131,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'com-seed-v3-crisis-line',
    category: AchievementCategory.community,
    title: 'Crisis Line Hours',
    description: 'Volunteered crisis line hours',
    xpValue: 143,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'com-seed-v3-clothing-drive',
    category: AchievementCategory.community,
    title: 'Clothing Drive',
    description: 'Ran a clothing drive',
    xpValue: 155,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'com-seed-v3-book-drive',
    category: AchievementCategory.community,
    title: 'Book Drive',
    description: 'Collected books for schools',
    xpValue: 167,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'com-seed-v3-park-trash',
    category: AchievementCategory.community,
    title: 'Park Trash Walk',
    description: 'Picked up trash on weekly walks',
    xpValue: 179,
    icon: 'diversity_3',
  ),
  Achievement(
    id: 'fun-seed-v3-wrong-meeting',
    category: AchievementCategory.funny,
    title: 'Wrong Meeting',
    description: 'Joined wrong video call five minutes',
    xpValue: 15,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-mute-fail',
    category: AchievementCategory.funny,
    title: 'Forgot Unmute',
    description: 'Presented while muted',
    xpValue: 21,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-camera-on',
    category: AchievementCategory.funny,
    title: 'Camera On Fail',
    description: 'Stood up while camera on',
    xpValue: 27,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-food-in-teeth',
    category: AchievementCategory.funny,
    title: 'Teeth Food',
    description: 'Talked with food in teeth',
    xpValue: 33,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-waved-wrong',
    category: AchievementCategory.funny,
    title: 'Wrong Wave',
    description: 'Waved at stranger enthusiastically',
    xpValue: 39,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-trip-public',
    category: AchievementCategory.funny,
    title: 'Public Trip',
    description: 'Tripped in public gracefully',
    xpValue: 45,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-wrong-name-tag',
    category: AchievementCategory.funny,
    title: 'Name Tag',
    description: 'Wore someone else\'s name tag',
    xpValue: 51,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-autocorrect-boss',
    category: AchievementCategory.funny,
    title: 'Boss Autocorrect',
    description: 'Autocorrected boss name',
    xpValue: 57,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-halloween-work',
    category: AchievementCategory.funny,
    title: 'Halloween Work',
    description: 'Wore costume to normal meeting',
    xpValue: 63,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-birthday-wrong-day',
    category: AchievementCategory.funny,
    title: 'Wrong Birthday',
    description: 'Celebrated wrong birthday',
    xpValue: 69,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-dog-ate-homework',
    category: AchievementCategory.funny,
    title: 'Dog Ate It',
    description: 'Blamed dog with proof',
    xpValue: 75,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-locked-bathroom',
    category: AchievementCategory.funny,
    title: 'Bathroom Lock',
    description: 'Got stuck in bathroom stall',
    xpValue: 81,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-wrong-order-name',
    category: AchievementCategory.funny,
    title: 'Coffee Name',
    description: 'Barista said wrong name proudly',
    xpValue: 87,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-selfie-stranger',
    category: AchievementCategory.funny,
    title: 'Stranger Photo',
    description: 'Photo bombed own selfie with stranger',
    xpValue: 93,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-seed-v3-lost-remote',
    category: AchievementCategory.funny,
    title: 'Remote Lost',
    description: 'Found remote in fridge',
    xpValue: 99,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'crt-seed-v3-ink-comic',
    category: AchievementCategory.creative,
    title: 'Comic Page',
    description: 'Published a comic page',
    xpValue: 35,
    icon: 'brush',
  ),
  Achievement(
    id: 'crt-seed-v3-pottery-sale',
    category: AchievementCategory.creative,
    title: 'Pottery Sale',
    description: 'Sold pottery piece',
    xpValue: 47,
    icon: 'brush',
  ),
  Achievement(
    id: 'crt-seed-v3-beat-drop',
    category: AchievementCategory.creative,
    title: 'Beat Release',
    description: 'Released an instrumental beat',
    xpValue: 59,
    icon: 'brush',
  ),
  Achievement(
    id: 'crt-seed-v3-cover-song',
    category: AchievementCategory.creative,
    title: 'Cover Song',
    description: 'Published a cover performance',
    xpValue: 71,
    icon: 'brush',
  ),
  Achievement(
    id: 'crt-seed-v3-graffiti-legal',
    category: AchievementCategory.creative,
    title: 'Legal Mural Assist',
    description: 'Assisted legal mural project',
    xpValue: 83,
    icon: 'brush',
  ),
  Achievement(
    id: 'crt-seed-v3-photo-print',
    category: AchievementCategory.creative,
    title: 'Photo Print Show',
    description: 'Printed photos for show',
    xpValue: 95,
    icon: 'brush',
  ),
  Achievement(
    id: 'crt-seed-v3-screenplay',
    category: AchievementCategory.creative,
    title: 'Screenplay Draft',
    description: 'Finished screenplay draft',
    xpValue: 107,
    icon: 'brush',
  ),
  Achievement(
    id: 'crt-seed-v3-story-public',
    category: AchievementCategory.creative,
    title: 'Story Published',
    description: 'Published short story',
    xpValue: 119,
    icon: 'brush',
  ),
  Achievement(
    id: 'crt-seed-v3-ui-kit',
    category: AchievementCategory.creative,
    title: 'UI Kit Free',
    description: 'Released free UI kit',
    xpValue: 131,
    icon: 'brush',
  ),
  Achievement(
    id: 'crt-seed-v3-crochet-gift',
    category: AchievementCategory.creative,
    title: 'Crochet Gift',
    description: 'Crocheted gift collection',
    xpValue: 143,
    icon: 'brush',
  ),
  Achievement(
    id: 'life-seed-v3-first-plant-kill',
    category: AchievementCategory.life,
    title: 'Plant Redemption',
    description: 'Revived a dying plant',
    xpValue: 35,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-birthday-surprise',
    category: AchievementCategory.life,
    title: 'Surprise Party',
    description: 'Pulled off surprise party',
    xpValue: 47,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-roadtrip-playlist',
    category: AchievementCategory.life,
    title: 'Road Playlist',
    description: 'Made legendary road playlist',
    xpValue: 59,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-thrift-wedding',
    category: AchievementCategory.life,
    title: 'Thrift Fit',
    description: 'Thrifted event outfit',
    xpValue: 71,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-learn-parent-recipe',
    category: AchievementCategory.life,
    title: 'Parent Recipe',
    description: 'Cooked parent recipe from memory',
    xpValue: 83,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-fix-appliance',
    category: AchievementCategory.life,
    title: 'Appliance Fix',
    description: 'Fixed appliance yourself',
    xpValue: 95,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-build-ikea-solo',
    category: AchievementCategory.life,
    title: 'IKEA Solo',
    description: 'Built IKEA furniture solo',
    xpValue: 107,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-mailbox-upgrade',
    category: AchievementCategory.life,
    title: 'Mailbox Glow',
    description: 'Upgraded curb appeal mailbox',
    xpValue: 119,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-balcony-lights',
    category: AchievementCategory.life,
    title: 'Balcony Lights',
    description: 'Strung balcony lights',
    xpValue: 131,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-rainy-walk',
    category: AchievementCategory.life,
    title: 'Rain Walk',
    description: 'Walked happily in rain',
    xpValue: 143,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-meteor-shower',
    category: AchievementCategory.life,
    title: 'Meteor Night',
    description: 'Watched meteor shower',
    xpValue: 155,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-local-tourist',
    category: AchievementCategory.life,
    title: 'Local Tourist',
    description: 'Tourist in own city for day',
    xpValue: 167,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-declutter-car',
    category: AchievementCategory.life,
    title: 'Clean Car',
    description: 'Deep cleaned car',
    xpValue: 179,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-friendship-bracelet',
    category: AchievementCategory.life,
    title: 'Friend Bracelets',
    description: 'Made friendship bracelets',
    xpValue: 191,
    icon: 'explore',
  ),
  Achievement(
    id: 'life-seed-v3-voice-memo',
    category: AchievementCategory.life,
    title: 'Voice Memo Diary',
    description: 'Kept voice memo diary month',
    xpValue: 203,
    icon: 'explore',
  ),
];
