import '../models/achievement.dart';

/// Fourth-wave catalog seeds — life, travel, funny, community (v4).
const List<Achievement> bulkAchievementSeedsV4 = [
  Achievement(
    id: 'life-seed-v4-first-apartment',
    category: AchievementCategory.life,
    title: 'First Apartment',
    description: 'Signed your first lease on your own',
    xpValue: 40,
    icon: 'home',
  ),
  Achievement(
    id: 'life-seed-v4-pet-parent',
    category: AchievementCategory.life,
    title: 'Pet Parent',
    description: 'Adopted or raised a pet',
    xpValue: 35,
    icon: 'pets',
  ),
  Achievement(
    id: 'life-seed-v4-drivers-license',
    category: AchievementCategory.life,
    title: 'Licensed Driver',
    description: 'Earned a valid driver license',
    xpValue: 30,
    icon: 'directions_car',
  ),
  Achievement(
    id: 'life-seed-v4-passport',
    category: AchievementCategory.life,
    title: 'Passport Holder',
    description: 'Received your first passport',
    xpValue: 45,
    icon: 'flight',
  ),
  Achievement(
    id: 'life-seed-v4-volunteer-100',
    category: AchievementCategory.life,
    title: '100 Volunteer Hours',
    description: 'Logged 100 hours of community service',
    xpValue: 55,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'life-seed-v4-sober-year',
    category: AchievementCategory.life,
    title: 'Sober Year',
    description: 'One year of intentional sobriety',
    xpValue: 80,
    icon: 'self_improvement',
  ),
  Achievement(
    id: 'life-seed-v4-side-hustle',
    category: AchievementCategory.life,
    title: 'Side Hustle',
    description: 'Launched a recurring side income stream',
    xpValue: 50,
    icon: 'payments',
  ),
  Achievement(
    id: 'life-seed-v4-citizenship',
    category: AchievementCategory.life,
    title: 'New Citizen',
    description: 'Completed naturalization or citizenship',
    xpValue: 90,
    icon: 'flag',
  ),
  Achievement(
    id: 'travel-seed-v4-first-flight',
    category: AchievementCategory.travel,
    title: 'First Flight',
    description: 'Flew on a commercial airplane',
    xpValue: 35,
    icon: 'flight_takeoff',
  ),
  Achievement(
    id: 'travel-seed-v4-three-countries',
    category: AchievementCategory.travel,
    title: 'Three Countries',
    description: 'Visited three different countries',
    xpValue: 60,
    icon: 'public',
  ),
  Achievement(
    id: 'travel-seed-v4-road-trip',
    category: AchievementCategory.travel,
    title: 'Epic Road Trip',
    description: 'Completed a multi-day road trip',
    xpValue: 45,
    icon: 'directions_car',
  ),
  Achievement(
    id: 'travel-seed-v4-national-park',
    category: AchievementCategory.travel,
    title: 'National Park',
    description: 'Visited a national park',
    xpValue: 40,
    icon: 'park',
  ),
  Achievement(
    id: 'travel-seed-v4-solo-travel',
    category: AchievementCategory.travel,
    title: 'Solo Traveler',
    description: 'Traveled alone to a new city',
    xpValue: 55,
    icon: 'hiking',
  ),
  Achievement(
    id: 'travel-seed-v4-backpack',
    category: AchievementCategory.travel,
    title: 'Backpacker',
    description: 'Traveled with only a backpack for a week+',
    xpValue: 65,
    icon: 'backpack',
  ),
  Achievement(
    id: 'funny-seed-v4-karaoke',
    category: AchievementCategory.funny,
    title: 'Karaoke Legend',
    description: 'Performed karaoke in public',
    xpValue: 25,
    icon: 'mic',
  ),
  Achievement(
    id: 'funny-seed-v4-meme-viral',
    category: AchievementCategory.funny,
    title: 'Viral Meme',
    description: 'A meme you made hit 10k+ views',
    xpValue: 30,
    icon: 'emoji_emotions',
  ),
  Achievement(
    id: 'funny-seed-v4-costume-win',
    category: AchievementCategory.funny,
    title: 'Costume Contest',
    description: 'Won or placed in a costume contest',
    xpValue: 28,
    icon: 'celebration',
  ),
  Achievement(
    id: 'funny-seed-v4-prank-wholesome',
    category: AchievementCategory.funny,
    title: 'Wholesome Prank',
    description: 'Pulled a harmless prank that made people laugh',
    xpValue: 22,
    icon: 'sentiment_very_satisfied',
  ),
  Achievement(
    id: 'funny-seed-v4-dad-joke',
    category: AchievementCategory.funny,
    title: 'Dad Joke Master',
    description: 'Delivered ten dad jokes that landed',
    xpValue: 20,
    icon: 'mood',
  ),
  Achievement(
    id: 'community-seed-v4-mentor',
    category: AchievementCategory.community,
    title: 'Mentor',
    description: 'Mentored someone for three months',
    xpValue: 70,
    icon: 'school',
  ),
  Achievement(
    id: 'community-seed-v4-organizer',
    category: AchievementCategory.community,
    title: 'Event Organizer',
    description: 'Organized a community event with 20+ attendees',
    xpValue: 65,
    icon: 'groups',
  ),
  Achievement(
    id: 'community-seed-v4-fundraiser',
    category: AchievementCategory.community,
    title: 'Fundraiser',
    description: 'Raised funds for a local cause',
    xpValue: 60,
    icon: 'favorite',
  ),
  Achievement(
    id: 'creative-seed-v4-published',
    category: AchievementCategory.creative,
    title: 'Published Work',
    description: 'Published creative work publicly',
    xpValue: 75,
    icon: 'auto_stories',
  ),
  Achievement(
    id: 'creative-seed-v4-exhibit',
    category: AchievementCategory.creative,
    title: 'Gallery Show',
    description: 'Displayed work in a show or exhibit',
    xpValue: 85,
    icon: 'palette',
  ),
  Achievement(
    id: 'creative-seed-v4-film-festival',
    category: AchievementCategory.creative,
    title: 'Film Festival',
    description: 'Screened a film at a festival',
    xpValue: 95,
    icon: 'movie',
  ),
  Achievement(
    id: 'skills-seed-v4-cpr',
    category: AchievementCategory.skills,
    title: 'CPR Certified',
    description: 'Completed CPR or first-aid certification',
    xpValue: 40,
    icon: 'medical_services',
  ),
  Achievement(
    id: 'skills-seed-v4-public-speaking',
    category: AchievementCategory.skills,
    title: 'Stage Speaker',
    description: 'Spoke to an audience of 50+',
    xpValue: 55,
    icon: 'record_voice_over',
  ),
  Achievement(
    id: 'finance-seed-v4-emergency-fund',
    category: AchievementCategory.finance,
    title: 'Emergency Fund',
    description: 'Saved three months of expenses',
    xpValue: 80,
    icon: 'savings',
  ),
  Achievement(
    id: 'finance-seed-v4-debt-free',
    category: AchievementCategory.finance,
    title: 'Debt Free',
    description: 'Paid off non-mortgage consumer debt',
    xpValue: 100,
    icon: 'account_balance_wallet',
  ),
];
