import '../models/achievement.dart';

/// Bulk catalog seeds — proof rules applied via [resolveAchievementCatalog].
const List<Achievement> bulkAchievementSeeds = [
  Achievement(
    id: 'edu-seed-honors-roll',
    category: AchievementCategory.education,
    title: 'Honors Roll',
    description: 'Made dean\'s list or equivalent honors',
    xpValue: 40,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-trade-school',
    category: AchievementCategory.education,
    title: 'Trade School Graduate',
    description: 'Completed vocational or trade program',
    xpValue: 61,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-bootcamp',
    category: AchievementCategory.education,
    title: 'Bootcamp Graduate',
    description: 'Finished an intensive skills bootcamp',
    xpValue: 82,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-online-degree',
    category: AchievementCategory.education,
    title: 'Online Degree',
    description: 'Earned a degree through accredited online study',
    xpValue: 103,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-study-abroad-edu',
    category: AchievementCategory.education,
    title: 'Study Abroad Scholar',
    description: 'Completed a semester or year abroad for school',
    xpValue: 124,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-thesis-defense',
    category: AchievementCategory.education,
    title: 'Thesis Defender',
    description: 'Successfully defended a thesis or capstone',
    xpValue: 145,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-teaching-cert',
    category: AchievementCategory.education,
    title: 'Teaching Certificate',
    description: 'Earned a teaching or instructor credential',
    xpValue: 167,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-stem-olympiad',
    category: AchievementCategory.education,
    title: 'STEM Competitor',
    description: 'Competed in a recognized STEM olympiad or fair',
    xpValue: 188,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-library-regular',
    category: AchievementCategory.education,
    title: 'Library Regular',
    description: 'Logged sustained independent study (library, lab, cohort)',
    xpValue: 209,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-tutor-certified',
    category: AchievementCategory.education,
    title: 'Certified Tutor',
    description: 'Became a certified peer or professional tutor',
    xpValue: 230,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-research-pub',
    category: AchievementCategory.education,
    title: 'Research Published',
    description: 'Co-authored or published academic research',
    xpValue: 251,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-language-fluent',
    category: AchievementCategory.education,
    title: 'Conversational Fluency',
    description: 'Reached conversational fluency in a new language',
    xpValue: 272,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-continuing-ed',
    category: AchievementCategory.education,
    title: 'Continuing Education',
    description: 'Completed continuing education for your field',
    xpValue: 294,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-scholarship',
    category: AchievementCategory.education,
    title: 'Scholarship Winner',
    description: 'Won a competitive academic scholarship',
    xpValue: 315,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-grad-speaker',
    category: AchievementCategory.education,
    title: 'Graduation Speaker',
    description: 'Spoke at a graduation or major academic ceremony',
    xpValue: 336,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-dual-major',
    category: AchievementCategory.education,
    title: 'Dual Major',
    description: 'Completed two majors or equivalent dual track',
    xpValue: 357,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-summer-intensive',
    category: AchievementCategory.education,
    title: 'Summer Intensive',
    description: 'Finished a competitive summer academic program',
    xpValue: 378,
    icon: 'school',
  ),
  Achievement(
    id: 'edu-seed-mentor-edu',
    category: AchievementCategory.education,
    title: 'Academic Mentor',
    description: 'Mentored students in a formal program',
    xpValue: 400,
    icon: 'school',
  ),
  Achievement(
    id: 'car-seed-first-intern',
    category: AchievementCategory.career,
    title: 'First Internship',
    description: 'Completed your first professional internship',
    xpValue: 50,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-promotion',
    category: AchievementCategory.career,
    title: 'Promotion Earned',
    description: 'Received a formal promotion',
    xpValue: 73,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-manager',
    category: AchievementCategory.career,
    title: 'People Manager',
    description: 'Started managing a team',
    xpValue: 97,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-remote-year',
    category: AchievementCategory.career,
    title: 'Remote Year',
    description: 'Worked remotely for a full year',
    xpValue: 120,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-startup-join',
    category: AchievementCategory.career,
    title: 'Startup Joiner',
    description: 'Joined an early-stage startup',
    xpValue: 144,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-enterprise-hire',
    category: AchievementCategory.career,
    title: 'Enterprise Hire',
    description: 'Hired into a large enterprise org',
    xpValue: 167,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-consultant',
    category: AchievementCategory.career,
    title: 'Independent Consultant',
    description: 'Launched independent consulting work',
    xpValue: 191,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-board-seat',
    category: AchievementCategory.career,
    title: 'Board Advisor',
    description: 'Joined a board or advisory council',
    xpValue: 214,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-patent-work',
    category: AchievementCategory.career,
    title: 'Patent Contributor',
    description: 'Contributed to a filed patent at work',
    xpValue: 238,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-conference-speaker',
    category: AchievementCategory.career,
    title: 'Conference Speaker',
    description: 'Spoke at an industry conference',
    xpValue: 261,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-cert-pro',
    category: AchievementCategory.career,
    title: 'Professional Certification',
    description: 'Earned a major industry certification',
    xpValue: 285,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-sales-quota',
    category: AchievementCategory.career,
    title: 'Quota Crusher',
    description: 'Hit or exceeded a major sales quota',
    xpValue: 308,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-on-call-hero',
    category: AchievementCategory.career,
    title: 'On-Call Hero',
    description: 'Resolved a critical production incident',
    xpValue: 332,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-mentor-work',
    category: AchievementCategory.career,
    title: 'Workplace Mentor',
    description: 'Formally mentored a colleague',
    xpValue: 355,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-union-rep',
    category: AchievementCategory.career,
    title: 'Union Representative',
    description: 'Served as a union or worker representative',
    xpValue: 379,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-apprentice-done',
    category: AchievementCategory.career,
    title: 'Apprenticeship Complete',
    description: 'Finished a registered apprenticeship',
    xpValue: 402,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-freelance-100',
    category: AchievementCategory.career,
    title: 'Freelance Century',
    description: 'Completed 100 paid freelance projects',
    xpValue: 426,
    icon: 'work',
  ),
  Achievement(
    id: 'car-seed-exit-interview',
    category: AchievementCategory.career,
    title: 'Graceful Exit',
    description: 'Left a role on excellent terms with references',
    xpValue: 450,
    icon: 'work',
  ),
  Achievement(
    id: 'rel-seed-first-date',
    category: AchievementCategory.relationships,
    title: 'First Date',
    description: 'Went on a memorable first date',
    xpValue: 40,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-anniversary-1',
    category: AchievementCategory.relationships,
    title: 'One Year Together',
    description: 'Celebrated one year as a couple',
    xpValue: 62,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-anniversary-5',
    category: AchievementCategory.relationships,
    title: 'Five Years Together',
    description: 'Celebrated five years as a couple',
    xpValue: 84,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-proposal',
    category: AchievementCategory.relationships,
    title: 'The Proposal',
    description: 'Got engaged or proposed',
    xpValue: 106,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-wedding',
    category: AchievementCategory.relationships,
    title: 'Wedding Day',
    description: 'Got married or had a commitment ceremony',
    xpValue: 128,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-new-parent',
    category: AchievementCategory.relationships,
    title: 'New Parent',
    description: 'Became a parent or guardian',
    xpValue: 150,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-reunion',
    category: AchievementCategory.relationships,
    title: 'Family Reunion',
    description: 'Attended a major family reunion',
    xpValue: 172,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-friendship-10',
    category: AchievementCategory.relationships,
    title: 'Decade Friend',
    description: 'Maintained a close friendship for 10+ years',
    xpValue: 195,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-roommate-era',
    category: AchievementCategory.relationships,
    title: 'Roommate Era',
    description: 'Lived with close friends successfully',
    xpValue: 217,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-pet-family',
    category: AchievementCategory.relationships,
    title: 'Pet Family',
    description: 'Adopted a pet that became family',
    xpValue: 239,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-long-distance',
    category: AchievementCategory.relationships,
    title: 'Long Distance',
    description: 'Made long-distance relationship work 1+ year',
    xpValue: 261,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-apology-master',
    category: AchievementCategory.relationships,
    title: 'Clean Apology',
    description: 'Repaired a relationship with a sincere apology',
    xpValue: 283,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-chosen-family',
    category: AchievementCategory.relationships,
    title: 'Chosen Family',
    description: 'Built a chosen-family support circle',
    xpValue: 305,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-sibling-bond',
    category: AchievementCategory.relationships,
    title: 'Sibling Bond',
    description: 'Strengthened sibling or kin relationship',
    xpValue: 327,
    icon: 'favorite',
  ),
  Achievement(
    id: 'rel-seed-community-wedding',
    category: AchievementCategory.relationships,
    title: 'Community Witness',
    description: 'Supported friends through wedding or union',
    xpValue: 350,
    icon: 'favorite',
  ),
  Achievement(
    id: 'hlth-seed-5k-run',
    category: AchievementCategory.health,
    title: 'First 5K',
    description: 'Finished a 5K run or walk',
    xpValue: 40,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-10k-run',
    category: AchievementCategory.health,
    title: 'First 10K',
    description: 'Finished a 10K event',
    xpValue: 61,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-half-marathon',
    category: AchievementCategory.health,
    title: 'Half Marathon',
    description: 'Finished a half marathon',
    xpValue: 82,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-marathon',
    category: AchievementCategory.health,
    title: 'Marathon Finisher',
    description: 'Finished a full marathon',
    xpValue: 103,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-sober-30',
    category: AchievementCategory.health,
    title: 'Sober 30',
    description: '30 days alcohol-free or sober milestone',
    xpValue: 124,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-sober-year',
    category: AchievementCategory.health,
    title: 'Sober Year',
    description: 'One year sober or substance-free milestone',
    xpValue: 145,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-sleep-fix',
    category: AchievementCategory.health,
    title: 'Sleep Reset',
    description: 'Improved sleep hygiene for 30+ days',
    xpValue: 167,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-meal-prep',
    category: AchievementCategory.health,
    title: 'Meal Prep Streak',
    description: 'Meal prepped for four consecutive weeks',
    xpValue: 188,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-yoga-100',
    category: AchievementCategory.health,
    title: '100 Yoga Sessions',
    description: 'Completed 100 yoga sessions',
    xpValue: 209,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-steps-10k',
    category: AchievementCategory.health,
    title: '10K Steps Streak',
    description: 'Hit 10k steps daily for 30 days',
    xpValue: 230,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-therapy-start',
    category: AchievementCategory.health,
    title: 'Therapy Started',
    description: 'Started therapy or counseling',
    xpValue: 251,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-dentist-regular',
    category: AchievementCategory.health,
    title: 'Dental Regular',
    description: 'Kept dental checkups two years in a row',
    xpValue: 272,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-blood-donor-5',
    category: AchievementCategory.health,
    title: 'Repeat Donor',
    description: 'Donated blood five times',
    xpValue: 294,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-mobility-gain',
    category: AchievementCategory.health,
    title: 'Mobility Gain',
    description: 'Improved mobility through rehab or training',
    xpValue: 315,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-plant-diet',
    category: AchievementCategory.health,
    title: 'Plant-Forward Month',
    description: 'Ate plant-forward for 30 days',
    xpValue: 336,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-cold-plunge',
    category: AchievementCategory.health,
    title: 'Cold Plunge',
    description: 'Completed a guided cold exposure milestone',
    xpValue: 357,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-mobility-aid',
    category: AchievementCategory.health,
    title: 'Adaptive Athlete',
    description: 'Competed or trained with adaptive sports',
    xpValue: 378,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'hlth-seed-health-screen',
    category: AchievementCategory.health,
    title: 'Health Screening',
    description: 'Completed recommended health screening',
    xpValue: 400,
    icon: 'fitness_center',
  ),
  Achievement(
    id: 'skl-seed-first-commit',
    category: AchievementCategory.skills,
    title: 'First Open Source',
    description: 'Merged a contribution to open source',
    xpValue: 50,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-side-project-ship',
    category: AchievementCategory.skills,
    title: 'Shipped Side Project',
    description: 'Released a side project publicly',
    xpValue: 73,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-instrument-grade',
    category: AchievementCategory.skills,
    title: 'Music Grade',
    description: 'Passed a graded music exam',
    xpValue: 97,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-chef-course',
    category: AchievementCategory.skills,
    title: 'Chef Course',
    description: 'Completed a culinary course or certification',
    xpValue: 120,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-woodworking',
    category: AchievementCategory.skills,
    title: 'Woodworking Build',
    description: 'Built furniture or wood project',
    xpValue: 144,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-welding',
    category: AchievementCategory.skills,
    title: 'Welding Project',
    description: 'Completed a welding project',
    xpValue: 167,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-sewing',
    category: AchievementCategory.skills,
    title: 'Sewing Collection',
    description: 'Sewed a wearable collection',
    xpValue: 191,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-photography-exhibit',
    category: AchievementCategory.skills,
    title: 'Photo Exhibit',
    description: 'Displayed photos in a show or gallery',
    xpValue: 214,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-chess-rating',
    category: AchievementCategory.skills,
    title: 'Chess Rating',
    description: 'Reached a published chess rating milestone',
    xpValue: 238,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-martial-belt',
    category: AchievementCategory.skills,
    title: 'Martial Belt',
    description: 'Earned a martial arts belt or rank',
    xpValue: 261,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-language-b2',
    category: AchievementCategory.skills,
    title: 'B2 Language',
    description: 'Reached B2 level in a foreign language',
    xpValue: 285,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-public-speaking',
    category: AchievementCategory.skills,
    title: 'Stage Speaker',
    description: 'Spoke on stage to 50+ people',
    xpValue: 308,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-speed-typing',
    category: AchievementCategory.skills,
    title: 'Typing Speed',
    description: 'Hit a verified typing speed benchmark',
    xpValue: 332,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-home-repair',
    category: AchievementCategory.skills,
    title: 'Home Repair Pro',
    description: 'Completed major DIY home repair',
    xpValue: 355,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-3d-print',
    category: AchievementCategory.skills,
    title: '3D Print Ship',
    description: 'Designed and printed a functional 3D object',
    xpValue: 379,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-game-dev',
    category: AchievementCategory.skills,
    title: 'Indie Game',
    description: 'Published an indie game or demo',
    xpValue: 402,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-data-viz',
    category: AchievementCategory.skills,
    title: 'Data Story',
    description: 'Published an interactive data visualization',
    xpValue: 426,
    icon: 'code',
  ),
  Achievement(
    id: 'skl-seed-first-aid-cert',
    category: AchievementCategory.skills,
    title: 'First Aid Certified',
    description: 'Earned first aid or CPR certification',
    xpValue: 450,
    icon: 'code',
  ),
  Achievement(
    id: 'trv-seed-first-passport',
    category: AchievementCategory.travel,
    title: 'Passport Stamped',
    description: 'Got your first passport stamp',
    xpValue: 60,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-solo-trip',
    category: AchievementCategory.travel,
    title: 'Solo Trip',
    description: 'Traveled solo internationally or cross-country',
    xpValue: 91,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-backpack',
    category: AchievementCategory.travel,
    title: 'Backpacker',
    description: 'Backpacked for two weeks or more',
    xpValue: 122,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-cruise',
    category: AchievementCategory.travel,
    title: 'Cruise Voyager',
    description: 'Completed a cruise or ferry voyage',
    xpValue: 154,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-national-park',
    category: AchievementCategory.travel,
    title: 'National Park',
    description: 'Visited a national park',
    xpValue: 185,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-unesco',
    category: AchievementCategory.travel,
    title: 'UNESCO Site',
    description: 'Visited a UNESCO World Heritage site',
    xpValue: 217,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-digital-nomad',
    category: AchievementCategory.travel,
    title: 'Digital Nomad Month',
    description: 'Worked remotely from another country a month',
    xpValue: 248,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-train-trek',
    category: AchievementCategory.travel,
    title: 'Train Trek',
    description: 'Took a multi-day train journey',
    xpValue: 280,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-road-trip-coast',
    category: AchievementCategory.travel,
    title: 'Coast to Coast Drive',
    description: 'Drove coast to coast or equivalent',
    xpValue: 311,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-hostel-stay',
    category: AchievementCategory.travel,
    title: 'Hostel Nights',
    description: 'Stayed in hostels on a multi-city trip',
    xpValue: 342,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-winter-arctic',
    category: AchievementCategory.travel,
    title: 'Winter Expedition',
    description: 'Traveled to arctic or extreme winter locale',
    xpValue: 374,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-tropical-island',
    category: AchievementCategory.travel,
    title: 'Island Hopper',
    description: 'Visited multiple islands on one trip',
    xpValue: 405,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-food-tour',
    category: AchievementCategory.travel,
    title: 'Food Tour',
    description: 'Did a dedicated culinary travel tour',
    xpValue: 437,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-volunteer-travel',
    category: AchievementCategory.travel,
    title: 'Volunteer Travel',
    description: 'Traveled for volunteer or service work',
    xpValue: 468,
    icon: 'flight',
  ),
  Achievement(
    id: 'trv-seed-mile-high',
    category: AchievementCategory.travel,
    title: 'Mile High Club',
    description: 'Flew business or first on a long-haul (flex achievement)',
    xpValue: 500,
    icon: 'flight',
  ),
  Achievement(
    id: 'fin-seed-first-invest',
    category: AchievementCategory.finance,
    title: 'First Investment',
    description: 'Opened and funded an investment account',
    xpValue: 80,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-roth-max',
    category: AchievementCategory.finance,
    title: 'Roth Maxed',
    description: 'Maxed annual Roth or IRA contribution',
    xpValue: 117,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-401k-start',
    category: AchievementCategory.finance,
    title: '401k Started',
    description: 'Started employer retirement contributions',
    xpValue: 154,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-credit-750',
    category: AchievementCategory.finance,
    title: '750 Credit',
    description: 'Reached 750+ credit score',
    xpValue: 191,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-side-income',
    category: AchievementCategory.finance,
    title: 'Side Income',
    description: 'Earned meaningful side income one quarter',
    xpValue: 228,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-tax-self',
    category: AchievementCategory.finance,
    title: 'Self-Filed Taxes',
    description: 'Filed taxes yourself successfully',
    xpValue: 265,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-will-written',
    category: AchievementCategory.finance,
    title: 'Estate Plan',
    description: 'Created a will or estate plan',
    xpValue: 302,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-insurance-review',
    category: AchievementCategory.finance,
    title: 'Coverage Review',
    description: 'Reviewed and updated insurance coverage',
    xpValue: 340,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-budget-year',
    category: AchievementCategory.finance,
    title: 'Budget Year',
    description: 'Stuck to a written budget 12 months',
    xpValue: 377,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-charity-give',
    category: AchievementCategory.finance,
    title: 'Charitable Giving',
    description: 'Donated 5%+ of income to charity one year',
    xpValue: 414,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-no-spend-month',
    category: AchievementCategory.finance,
    title: 'No-Spend Month',
    description: 'Completed a no-spend or low-spend month',
    xpValue: 451,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-refinance',
    category: AchievementCategory.finance,
    title: 'Refinance Win',
    description: 'Refinanced debt for lower rate',
    xpValue: 488,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-business-account',
    category: AchievementCategory.finance,
    title: 'Business Banking',
    description: 'Opened dedicated business banking',
    xpValue: 525,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-grant-won',
    category: AchievementCategory.finance,
    title: 'Grant Winner',
    description: 'Won a business or research grant',
    xpValue: 562,
    icon: 'savings',
  ),
  Achievement(
    id: 'fin-seed-net-worth-track',
    category: AchievementCategory.finance,
    title: 'Net Worth Tracker',
    description: 'Tracked net worth monthly for a year',
    xpValue: 600,
    icon: 'savings',
  ),
  Achievement(
    id: 'com-seed-food-bank',
    category: AchievementCategory.community,
    title: 'Food Bank Shifts',
    description: 'Volunteered at a food bank regularly',
    xpValue: 40,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-habitat',
    category: AchievementCategory.community,
    title: 'Habitat Build',
    description: 'Built with habitat or housing charity',
    xpValue: 62,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-coach-youth',
    category: AchievementCategory.community,
    title: 'Youth Coach',
    description: 'Coached youth sports or activities',
    xpValue: 84,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-tutor-free',
    category: AchievementCategory.community,
    title: 'Free Tutor',
    description: 'Tutored students for free',
    xpValue: 106,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-neighborhood-watch',
    category: AchievementCategory.community,
    title: 'Neighborhood Watch',
    description: 'Joined neighborhood safety or mutual aid',
    xpValue: 128,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-fundraiser-host',
    category: AchievementCategory.community,
    title: 'Fundraiser Host',
    description: 'Hosted a fundraiser event',
    xpValue: 150,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-cleanup-park',
    category: AchievementCategory.community,
    title: 'Park Cleanup',
    description: 'Led or joined a park cleanup',
    xpValue: 172,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-elder-visit',
    category: AchievementCategory.community,
    title: 'Elder Visits',
    description: 'Visited elders monthly for six months',
    xpValue: 195,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-animal-shelter',
    category: AchievementCategory.community,
    title: 'Shelter Volunteer',
    description: 'Volunteered at an animal shelter',
    xpValue: 217,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-disaster-relief',
    category: AchievementCategory.community,
    title: 'Disaster Relief',
    description: 'Helped in disaster relief efforts',
    xpValue: 239,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-town-hall',
    category: AchievementCategory.community,
    title: 'Town Hall Voice',
    description: 'Spoke at a local town hall or council',
    xpValue: 261,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-mutual-aid',
    category: AchievementCategory.community,
    title: 'Mutual Aid',
    description: 'Organized mutual aid for your block or community',
    xpValue: 283,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-library-vol',
    category: AchievementCategory.community,
    title: 'Library Volunteer',
    description: 'Volunteered at a public library',
    xpValue: 305,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-mentor-big',
    category: AchievementCategory.community,
    title: 'Big Mentor',
    description: 'Mentored through a formal big-sibling style program',
    xpValue: 327,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'com-seed-community-garden',
    category: AchievementCategory.community,
    title: 'Community Garden',
    description: 'Started or sustained a community garden plot',
    xpValue: 350,
    icon: 'volunteer_activism',
  ),
  Achievement(
    id: 'fun-seed-sent-text-wrong',
    category: AchievementCategory.funny,
    title: 'Wrong Chat',
    description: 'Sent a text to the wrong person',
    xpValue: 25,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-autocorrect-fail',
    category: AchievementCategory.funny,
    title: 'Autocorrect Victim',
    description: 'Autocorrect ruined a serious message',
    xpValue: 34,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-walked-in',
    category: AchievementCategory.funny,
    title: 'Walked Into Glass',
    description: 'Walked into a glass door in public',
    xpValue: 43,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-wifi-name',
    category: AchievementCategory.funny,
    title: 'Funny Wi-Fi Name',
    description: 'Named your Wi-Fi something unhinged',
    xpValue: 52,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-pet-witness',
    category: AchievementCategory.funny,
    title: 'Pet Witness',
    description: 'Your pet saw something they should not have',
    xpValue: 61,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-costume-grocery',
    category: AchievementCategory.funny,
    title: 'Grocery Costume',
    description: 'Wore a costume to a mundane errand',
    xpValue: 71,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-google-self',
    category: AchievementCategory.funny,
    title: 'Googled Yourself',
    description: 'Googled yourself and regretted it',
    xpValue: 80,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-reply-all',
    category: AchievementCategory.funny,
    title: 'Reply All Disaster',
    description: 'Hit reply-all by accident',
    xpValue: 89,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-food-floor',
    category: AchievementCategory.funny,
    title: 'Five Second Rule',
    description: 'Ate something after the five-second rule',
    xpValue: 98,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-alarm-snooze',
    category: AchievementCategory.funny,
    title: 'Snooze Champion',
    description: 'Snoozed an alarm ten times in one morning',
    xpValue: 107,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-name-wrong',
    category: AchievementCategory.funny,
    title: 'Name Wrong',
    description: 'Called someone the wrong name confidently',
    xpValue: 117,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-zoom-filter',
    category: AchievementCategory.funny,
    title: 'Zoom Filter Stuck',
    description: 'Joined a call with a filter stuck on',
    xpValue: 126,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-laundry-mix',
    category: AchievementCategory.funny,
    title: 'Pink Laundry',
    description: 'Turned an entire load pink',
    xpValue: 135,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-gps-lake',
    category: AchievementCategory.funny,
    title: 'GPS to Lake',
    description: 'Followed GPS into an absurd detour',
    xpValue: 144,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-ikea-leftover',
    category: AchievementCategory.funny,
    title: 'IKEA Leftovers',
    description: 'Have mysterious IKEA hardware forever',
    xpValue: 153,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-plant-kill',
    category: AchievementCategory.funny,
    title: 'Plant Assassin',
    description: 'Killed a supposedly easy plant',
    xpValue: 163,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-group-chat',
    category: AchievementCategory.funny,
    title: 'Group Chat Menace',
    description: 'Sent a meme at the worst possible time',
    xpValue: 172,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-selfie-fail',
    category: AchievementCategory.funny,
    title: 'Selfie Fail',
    description: 'Took 50 selfies and liked none',
    xpValue: 181,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-fridge-science',
    category: AchievementCategory.funny,
    title: 'Fridge Science',
    description: 'Found expired food from another era',
    xpValue: 190,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'fun-seed-sock-lost',
    category: AchievementCategory.funny,
    title: 'Sock Dimension',
    description: 'Lost a sock in a closed dryer',
    xpValue: 200,
    isFunny: true,
    icon: 'mood',
  ),
  Achievement(
    id: 'crt-seed-album-release',
    category: AchievementCategory.creative,
    title: 'Album Release',
    description: 'Released a music album or EP',
    xpValue: 50,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-gallery-show',
    category: AchievementCategory.creative,
    title: 'Gallery Show',
    description: 'Showed work in a gallery or pop-up',
    xpValue: 75,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-short-film',
    category: AchievementCategory.creative,
    title: 'Short Film',
    description: 'Premiered a short film',
    xpValue: 100,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-podcast-launch',
    category: AchievementCategory.creative,
    title: 'Podcast Launch',
    description: 'Published ten podcast episodes',
    xpValue: 125,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-newsletter-1k',
    category: AchievementCategory.creative,
    title: 'Newsletter 1K',
    description: 'Reached 1,000 newsletter subscribers',
    xpValue: 150,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-commission-art',
    category: AchievementCategory.creative,
    title: 'Paid Commission',
    description: 'Completed paid art commissions',
    xpValue: 175,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-etsy-shop',
    category: AchievementCategory.creative,
    title: 'Shop Opened',
    description: 'Opened a creative shop with sales',
    xpValue: 200,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-book-launch',
    category: AchievementCategory.creative,
    title: 'Book Launch',
    description: 'Launched a published book',
    xpValue: 225,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-theater-run',
    category: AchievementCategory.creative,
    title: 'Theater Run',
    description: 'Performed in a theater run',
    xpValue: 250,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-design-system',
    category: AchievementCategory.creative,
    title: 'Design System',
    description: 'Shipped a design system publicly',
    xpValue: 275,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-tattoo-art',
    category: AchievementCategory.creative,
    title: 'Tattoo Art',
    description: 'Designed tattoo art professionally',
    xpValue: 300,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-fashion-line',
    category: AchievementCategory.creative,
    title: 'Fashion Drop',
    description: 'Dropped a fashion or merch line',
    xpValue: 325,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-game-art',
    category: AchievementCategory.creative,
    title: 'Game Art',
    description: 'Shipped art for a shipped game',
    xpValue: 350,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-mural',
    category: AchievementCategory.creative,
    title: 'Public Mural',
    description: 'Painted a public mural',
    xpValue: 375,
    icon: 'palette',
  ),
  Achievement(
    id: 'crt-seed-viral-post',
    category: AchievementCategory.creative,
    title: 'Viral Creative Post',
    description: 'Creative post crossed 100k views',
    xpValue: 400,
    icon: 'palette',
  ),
  Achievement(
    id: 'life-seed-moved-cities',
    category: AchievementCategory.life,
    title: 'City Move',
    description: 'Moved to a new city',
    xpValue: 30,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-first-apartment',
    category: AchievementCategory.life,
    title: 'First Apartment',
    description: 'Signed your first solo lease',
    xpValue: 41,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-learned-drive',
    category: AchievementCategory.life,
    title: 'Learned to Drive',
    description: 'Got your driver\'s license',
    xpValue: 52,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-adopted-pet',
    category: AchievementCategory.life,
    title: 'Pet Adoption',
    description: 'Adopted a pet',
    xpValue: 63,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-quit-habit',
    category: AchievementCategory.life,
    title: 'Quit a Habit',
    description: 'Quit a habit for 90 days',
    xpValue: 75,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-deep-clean',
    category: AchievementCategory.life,
    title: 'Deep Clean',
    description: 'Deep-cleaned your entire living space',
    xpValue: 86,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-digital-detox',
    category: AchievementCategory.life,
    title: 'Digital Detox',
    description: 'Did a 72-hour digital detox',
    xpValue: 97,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-cooked-feast',
    category: AchievementCategory.life,
    title: 'Feast Host',
    description: 'Hosted a dinner for eight or more',
    xpValue: 108,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-learned-recipe',
    category: AchievementCategory.life,
    title: 'Signature Dish',
    description: 'Mastered a signature dish',
    xpValue: 120,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-festival-goer',
    category: AchievementCategory.life,
    title: 'Festival Goer',
    description: 'Attended a multi-day festival',
    xpValue: 131,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-concert-front',
    category: AchievementCategory.life,
    title: 'Front Row',
    description: 'Got front row at a live show',
    xpValue: 142,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-thrift-score',
    category: AchievementCategory.life,
    title: 'Thrift Score',
    description: 'Found an incredible thrift score',
    xpValue: 153,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-closet-purge',
    category: AchievementCategory.life,
    title: 'Closet Purge',
    description: 'Donated half your wardrobe',
    xpValue: 165,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-journal-year',
    category: AchievementCategory.life,
    title: 'Journal Year',
    description: 'Journaled most days for a year',
    xpValue: 176,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-sunrise-chaser',
    category: AchievementCategory.life,
    title: 'Sunrise Chaser',
    description: 'Watched sunrise from a special place',
    xpValue: 187,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-storm-watcher',
    category: AchievementCategory.life,
    title: 'Storm Watcher',
    description: 'Witnessed a major storm safely',
    xpValue: 198,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-snow-day',
    category: AchievementCategory.life,
    title: 'Snow Day',
    description: 'Had a legendary snow day',
    xpValue: 210,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-heat-wave',
    category: AchievementCategory.life,
    title: 'Heat Wave Survivor',
    description: 'Survived a brutal heat wave',
    xpValue: 221,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-power-outage',
    category: AchievementCategory.life,
    title: 'Power Outage Camp',
    description: 'Made a power outage fun',
    xpValue: 232,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-neighbor-friends',
    category: AchievementCategory.life,
    title: 'Neighbor Friends',
    description: 'Became friends with neighbors',
    xpValue: 243,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-bike-commute',
    category: AchievementCategory.life,
    title: 'Bike Commute Month',
    description: 'Biked to work a full month',
    xpValue: 255,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-minimalist-month',
    category: AchievementCategory.life,
    title: 'Minimalist Month',
    description: 'Lived minimally for 30 days',
    xpValue: 266,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-photo-a-day',
    category: AchievementCategory.life,
    title: 'Photo a Day',
    description: 'Took a photo every day for 100 days',
    xpValue: 277,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-letters-written',
    category: AchievementCategory.life,
    title: 'Letters Written',
    description: 'Wrote ten handwritten letters',
    xpValue: 288,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'life-seed-time-capsule',
    category: AchievementCategory.life,
    title: 'Time Capsule',
    description: 'Buried or sealed a time capsule',
    xpValue: 300,
    icon: 'auto_awesome',
  ),
  Achievement(
    id: 'prof-nurse',
    category: AchievementCategory.profession,
    title: 'Verified Nurse',
    description: 'Verified nursing professional',
    xpValue: 150,
    icon: 'verified',
  ),
  Achievement(
    id: 'prof-teacher',
    category: AchievementCategory.profession,
    title: 'Verified Teacher',
    description: 'Verified teaching professional',
    xpValue: 164,
    icon: 'verified',
  ),
  Achievement(
    id: 'prof-architect',
    category: AchievementCategory.profession,
    title: 'Verified Architect',
    description: 'Verified architecture professional',
    xpValue: 178,
    icon: 'verified',
  ),
  Achievement(
    id: 'prof-scientist',
    category: AchievementCategory.profession,
    title: 'Verified Scientist',
    description: 'Verified research scientist',
    xpValue: 192,
    icon: 'verified',
  ),
  Achievement(
    id: 'prof-chef',
    category: AchievementCategory.profession,
    title: 'Verified Chef',
    description: 'Verified culinary professional',
    xpValue: 207,
    icon: 'verified',
  ),
  Achievement(
    id: 'prof-realtor',
    category: AchievementCategory.profession,
    title: 'Verified Realtor',
    description: 'Verified real estate professional',
    xpValue: 221,
    icon: 'verified',
  ),
  Achievement(
    id: 'prof-therapist',
    category: AchievementCategory.profession,
    title: 'Verified Therapist',
    description: 'Verified mental health professional',
    xpValue: 235,
    icon: 'verified',
  ),
  Achievement(
    id: 'prof-journalist',
    category: AchievementCategory.profession,
    title: 'Verified Journalist',
    description: 'Verified journalism professional',
    xpValue: 250,
    icon: 'verified',
  ),
];
