import '../models/achievement.dart';

/// Second-wave catalog seeds (extended milestones).
const List<Achievement> bulkAchievementSeedsV2 = [
  Achievement(
    id: 'edu-ext-ext-library-card',
    category: AchievementCategory.education,
    title: 'Library Card Legend',
    description: 'Held an active library card for five years',
    xpValue: 40,
    icon: 'menu_book',
  ),
  Achievement(
    id: 'edu-ext-ext-study-group',
    category: AchievementCategory.education,
    title: 'Study Group Founder',
    description: 'Started a recurring study group',
    xpValue: 55,
    icon: 'menu_book',
  ),
  Achievement(
    id: 'edu-ext-ext-math-olympiad',
    category: AchievementCategory.education,
    title: 'Math League',
    description: 'Competed in regional math league',
    xpValue: 70,
    icon: 'menu_book',
  ),
  Achievement(
    id: 'edu-ext-ext-science-fair',
    category: AchievementCategory.education,
    title: 'Science Fair Judge',
    description: 'Judged or won a regional science fair',
    xpValue: 85,
    icon: 'menu_book',
  ),
  Achievement(
    id: 'edu-ext-ext-debate',
    category: AchievementCategory.education,
    title: 'Debate Captain',
    description: 'Led a competitive debate team',
    xpValue: 100,
    icon: 'menu_book',
  ),
  Achievement(
    id: 'edu-ext-ext-history-prize',
    category: AchievementCategory.education,
    title: 'History Prize',
    description: 'Won a history or humanities prize',
    xpValue: 115,
    icon: 'menu_book',
  ),
  Achievement(
    id: 'edu-ext-ext-coding-club',
    category: AchievementCategory.education,
    title: 'CS Club Lead',
    description: 'Led a school or university CS club',
    xpValue: 130,
    icon: 'menu_book',
  ),
  Achievement(
    id: 'edu-ext-ext-exchange',
    category: AchievementCategory.education,
    title: 'Exchange Student',
    description: 'Completed a student exchange program',
    xpValue: 145,
    icon: 'menu_book',
  ),
  Achievement(
    id: 'edu-ext-ext-lab-tech',
    category: AchievementCategory.education,
    title: 'Lab Tech Certified',
    description: 'Certified as a lab technician',
    xpValue: 160,
    icon: 'menu_book',
  ),
  Achievement(
    id: 'edu-ext-ext-museum-guide',
    category: AchievementCategory.education,
    title: 'Museum Docent',
    description: 'Volunteered as a museum docent',
    xpValue: 175,
    icon: 'menu_book',
  ),
  Achievement(
    id: 'edu-ext-ext-typing-cert',
    category: AchievementCategory.education,
    title: 'Typing Certified',
    description: 'Passed a professional typing certification',
    xpValue: 190,
    icon: 'menu_book',
  ),
  Achievement(
    id: 'edu-ext-ext-grad-with-distinction',
    category: AchievementCategory.education,
    title: 'With Distinction',
    description: 'Graduated with highest distinction',
    xpValue: 205,
    icon: 'menu_book',
  ),
  Achievement(
    id: 'car-ext-ext-standup-lead',
    category: AchievementCategory.career,
    title: 'Standup Lead',
    description: 'Ran daily standups for a quarter',
    xpValue: 40,
    icon: 'corporate_fare',
  ),
  Achievement(
    id: 'car-ext-ext-incident-postmortem',
    category: AchievementCategory.career,
    title: 'Postmortem Author',
    description: 'Authored a blameless incident postmortem',
    xpValue: 55,
    icon: 'corporate_fare',
  ),
  Achievement(
    id: 'car-ext-ext-hack-week',
    category: AchievementCategory.career,
    title: 'Hack Week Winner',
    description: 'Won an internal hack week',
    xpValue: 70,
    icon: 'corporate_fare',
  ),
  Achievement(
    id: 'car-ext-ext-mentorship-program',
    category: AchievementCategory.career,
    title: 'Mentorship Program',
    description: 'Joined a formal corporate mentorship program',
    xpValue: 85,
    icon: 'corporate_fare',
  ),
  Achievement(
    id: 'car-ext-ext-esop',
    category: AchievementCategory.career,
    title: 'Equity Holder',
    description: 'Received meaningful equity compensation',
    xpValue: 100,
    icon: 'corporate_fare',
  ),
  Achievement(
    id: 'car-ext-ext-sabbatical',
    category: AchievementCategory.career,
    title: 'Sabbatical Taker',
    description: 'Took a paid sabbatical',
    xpValue: 115,
    icon: 'corporate_fare',
  ),
  Achievement(
    id: 'car-ext-ext-returnship',
    category: AchievementCategory.career,
    title: 'Returnship Complete',
    description: 'Completed a return-to-work program',
    xpValue: 130,
    icon: 'corporate_fare',
  ),
  Achievement(
    id: 'car-ext-ext-union-bargain',
    category: AchievementCategory.career,
    title: 'Bargaining Team',
    description: 'Participated in contract bargaining',
    xpValue: 145,
    icon: 'corporate_fare',
  ),
  Achievement(
    id: 'car-ext-ext-trade-show',
    category: AchievementCategory.career,
    title: 'Trade Show Rep',
    description: 'Represented company at a major trade show',
    xpValue: 160,
    icon: 'corporate_fare',
  ),
  Achievement(
    id: 'car-ext-ext-press-quote',
    category: AchievementCategory.career,
    title: 'Press Quote',
    description: 'Quoted in industry press for your work',
    xpValue: 175,
    icon: 'corporate_fare',
  ),
  Achievement(
    id: 'car-ext-ext-open-source-work',
    category: AchievementCategory.career,
    title: 'OSS at Work',
    description: 'Shipped open source on company time',
    xpValue: 190,
    icon: 'corporate_fare',
  ),
  Achievement(
    id: 'car-ext-ext-exit-bonus',
    category: AchievementCategory.career,
    title: 'Retention Win',
    description: 'Earned a retention or project completion bonus',
    xpValue: 205,
    icon: 'corporate_fare',
  ),
  Achievement(
    id: 'rel-ext-ext-blind-date-win',
    category: AchievementCategory.relationships,
    title: 'Blind Date Win',
    description: 'Blind date went surprisingly well',
    xpValue: 40,
    icon: 'people',
  ),
  Achievement(
    id: 'rel-ext-ext-anniversary-trip',
    category: AchievementCategory.relationships,
    title: 'Anniversary Trip',
    description: 'Took a dedicated anniversary trip',
    xpValue: 55,
    icon: 'people',
  ),
  Achievement(
    id: 'rel-ext-ext-grandparent-visit',
    category: AchievementCategory.relationships,
    title: 'Grandparent Visits',
    description: 'Visited grandparents monthly a year',
    xpValue: 70,
    icon: 'people',
  ),
  Achievement(
    id: 'rel-ext-ext-cousin-reconnect',
    category: AchievementCategory.relationships,
    title: 'Cousin Reconnect',
    description: 'Reconnected with extended family',
    xpValue: 85,
    icon: 'people',
  ),
  Achievement(
    id: 'rel-ext-ext-housewarming',
    category: AchievementCategory.relationships,
    title: 'Housewarming Host',
    description: 'Hosted a housewarming for friends',
    xpValue: 100,
    icon: 'people',
  ),
  Achievement(
    id: 'rel-ext-ext-breakup-growth',
    category: AchievementCategory.relationships,
    title: 'Growth After Goodbye',
    description: 'Documented growth after a respectful breakup',
    xpValue: 115,
    icon: 'people',
  ),
  Achievement(
    id: 'rel-ext-ext-pet-sitter',
    category: AchievementCategory.relationships,
    title: 'Pet Sitter Circle',
    description: 'Regularly sat pets for friends',
    xpValue: 130,
    icon: 'people',
  ),
  Achievement(
    id: 'rel-ext-ext-book-club-couple',
    category: AchievementCategory.relationships,
    title: 'Couples Book Club',
    description: 'Joined a couples book club',
    xpValue: 145,
    icon: 'people',
  ),
  Achievement(
    id: 'rel-ext-ext-vow-renewal',
    category: AchievementCategory.relationships,
    title: 'Vow Renewal',
    description: 'Renewed vows or commitments',
    xpValue: 160,
    icon: 'people',
  ),
  Achievement(
    id: 'rel-ext-ext-found-family-dinner',
    category: AchievementCategory.relationships,
    title: 'Chosen Family Dinner',
    description: 'Hosted monthly chosen-family dinners',
    xpValue: 175,
    icon: 'people',
  ),
  Achievement(
    id: 'hlth-ext-ext-ironman',
    category: AchievementCategory.health,
    title: 'Ironman Finisher',
    description: 'Finished a full Ironman',
    xpValue: 40,
    icon: 'spa',
  ),
  Achievement(
    id: 'hlth-ext-ext-century-ride',
    category: AchievementCategory.health,
    title: 'Century Ride',
    description: 'Completed a 100-mile bike ride',
    xpValue: 55,
    icon: 'spa',
  ),
  Achievement(
    id: 'hlth-ext-ext-row-5k',
    category: AchievementCategory.health,
    title: '5K Row',
    description: 'Rowed 5K under target pace',
    xpValue: 70,
    icon: 'spa',
  ),
  Achievement(
    id: 'hlth-ext-ext-climb-v4',
    category: AchievementCategory.health,
    title: 'Climbing V4',
    description: 'Climbed indoor V4 or equivalent',
    xpValue: 85,
    icon: 'spa',
  ),
  Achievement(
    id: 'hlth-ext-ext-pilates-50',
    category: AchievementCategory.health,
    title: '50 Pilates Classes',
    description: 'Completed 50 pilates sessions',
    xpValue: 100,
    icon: 'spa',
  ),
  Achievement(
    id: 'hlth-ext-ext-hydration-30',
    category: AchievementCategory.health,
    title: 'Hydration Streak',
    description: 'Hit hydration goals 30 days',
    xpValue: 115,
    icon: 'spa',
  ),
  Achievement(
    id: 'hlth-ext-ext-no-sugar-month',
    category: AchievementCategory.health,
    title: 'No Sugar Month',
    description: 'Avoided added sugar for 30 days',
    xpValue: 130,
    icon: 'spa',
  ),
  Achievement(
    id: 'hlth-ext-ext-posture-fix',
    category: AchievementCategory.health,
    title: 'Posture Reset',
    description: 'Fixed desk posture with ergo setup',
    xpValue: 145,
    icon: 'spa',
  ),
  Achievement(
    id: 'hlth-ext-ext-vision-exam',
    category: AchievementCategory.health,
    title: 'Vision Exam',
    description: 'Kept annual vision exams',
    xpValue: 160,
    icon: 'spa',
  ),
  Achievement(
    id: 'hlth-ext-ext-vaccine-catchup',
    category: AchievementCategory.health,
    title: 'Vaccine Catch-up',
    description: 'Caught up on recommended vaccines',
    xpValue: 175,
    icon: 'spa',
  ),
  Achievement(
    id: 'hlth-ext-ext-sauna-streak',
    category: AchievementCategory.health,
    title: 'Sauna Streak',
    description: 'Used sauna or heat therapy 10 sessions',
    xpValue: 190,
    icon: 'spa',
  ),
  Achievement(
    id: 'hlth-ext-ext-stretch-routine',
    category: AchievementCategory.health,
    title: 'Stretch Routine',
    description: 'Daily stretch routine for 60 days',
    xpValue: 205,
    icon: 'spa',
  ),
  Achievement(
    id: 'skl-ext-ext-pottery',
    category: AchievementCategory.skills,
    title: 'Pottery Kiln',
    description: 'Fired original pottery in a kiln',
    xpValue: 40,
    icon: 'construction',
  ),
  Achievement(
    id: 'skl-ext-ext-blacksmith',
    category: AchievementCategory.skills,
    title: 'Blacksmith Piece',
    description: 'Forged a functional metal piece',
    xpValue: 55,
    icon: 'construction',
  ),
  Achievement(
    id: 'skl-ext-ext-beekeeping',
    category: AchievementCategory.skills,
    title: 'Beekeeper',
    description: 'Maintained a beehive season',
    xpValue: 70,
    icon: 'construction',
  ),
  Achievement(
    id: 'skl-ext-ext-garden-harvest',
    category: AchievementCategory.skills,
    title: 'Garden Harvest',
    description: 'Harvested home garden produce',
    xpValue: 85,
    icon: 'construction',
  ),
  Achievement(
    id: 'skl-ext-ext-car-restore',
    category: AchievementCategory.skills,
    title: 'Car Restore',
    description: 'Restored a vehicle mechanically',
    xpValue: 100,
    icon: 'construction',
  ),
  Achievement(
    id: 'skl-ext-ext-radio-license',
    category: AchievementCategory.skills,
    title: 'Ham Radio',
    description: 'Earned amateur radio license',
    xpValue: 115,
    icon: 'construction',
  ),
  Achievement(
    id: 'skl-ext-ext-sailing',
    category: AchievementCategory.skills,
    title: 'Sailing Crew',
    description: 'Crewed on a sailing voyage',
    xpValue: 130,
    icon: 'construction',
  ),
  Achievement(
    id: 'skl-ext-ext-scuba',
    category: AchievementCategory.skills,
    title: 'Scuba Certified',
    description: 'Earned open water scuba certification',
    xpValue: 145,
    icon: 'construction',
  ),
  Achievement(
    id: 'skl-ext-ext-lockpick-ethical',
    category: AchievementCategory.skills,
    title: 'Locksport Ethical',
    description: 'Practiced ethical locksport',
    xpValue: 160,
    icon: 'construction',
  ),
  Achievement(
    id: 'skl-ext-ext-calligraphy',
    category: AchievementCategory.skills,
    title: 'Calligraphy Set',
    description: 'Completed a calligraphy portfolio',
    xpValue: 175,
    icon: 'construction',
  ),
  Achievement(
    id: 'skl-ext-ext-animation',
    category: AchievementCategory.skills,
    title: 'Animation Reel',
    description: 'Published an animation reel',
    xpValue: 190,
    icon: 'construction',
  ),
  Achievement(
    id: 'skl-ext-ext-bread-artisan',
    category: AchievementCategory.skills,
    title: 'Artisan Bread',
    description: 'Baked sourdough on schedule 8 weeks',
    xpValue: 205,
    icon: 'construction',
  ),
  Achievement(
    id: 'trv-ext-ext-border-cross',
    category: AchievementCategory.travel,
    title: 'Border Crosser',
    description: 'Crossed three borders in one trip',
    xpValue: 60,
    icon: 'explore',
  ),
  Achievement(
    id: 'trv-ext-ext-camping-week',
    category: AchievementCategory.travel,
    title: 'Camping Week',
    description: 'Camped outdoors for seven nights',
    xpValue: 75,
    icon: 'explore',
  ),
  Achievement(
    id: 'trv-ext-ext-hot-spring',
    category: AchievementCategory.travel,
    title: 'Hot Spring',
    description: 'Visited a natural hot spring',
    xpValue: 90,
    icon: 'explore',
  ),
  Achievement(
    id: 'trv-ext-ext-desert-camp',
    category: AchievementCategory.travel,
    title: 'Desert Camp',
    description: 'Camped in a desert landscape',
    xpValue: 105,
    icon: 'explore',
  ),
  Achievement(
    id: 'trv-ext-ext-ferry-islands',
    category: AchievementCategory.travel,
    title: 'Ferry Islands',
    description: 'Island-hopped by ferry',
    xpValue: 120,
    icon: 'explore',
  ),
  Achievement(
    id: 'trv-ext-ext-mountain-hut',
    category: AchievementCategory.travel,
    title: 'Mountain Hut',
    description: 'Stayed in an alpine hut',
    xpValue: 135,
    icon: 'explore',
  ),
  Achievement(
    id: 'trv-ext-ext-pilgrimage',
    category: AchievementCategory.travel,
    title: 'Pilgrimage Walk',
    description: 'Walked a pilgrimage route segment',
    xpValue: 150,
    icon: 'explore',
  ),
  Achievement(
    id: 'trv-ext-ext-photo-travel',
    category: AchievementCategory.travel,
    title: 'Travel Photo Series',
    description: 'Published a travel photo series',
    xpValue: 165,
    icon: 'explore',
  ),
  Achievement(
    id: 'trv-ext-ext-language-immersion',
    category: AchievementCategory.travel,
    title: 'Immersion Trip',
    description: 'Traveled for language immersion',
    xpValue: 180,
    icon: 'explore',
  ),
  Achievement(
    id: 'trv-ext-ext-zero-waste-trip',
    category: AchievementCategory.travel,
    title: 'Low-Waste Trip',
    description: 'Completed a low-waste travel week',
    xpValue: 195,
    icon: 'explore',
  ),
  Achievement(
    id: 'fin-ext-ext-hsa-max',
    category: AchievementCategory.finance,
    title: 'HSA Maxed',
    description: 'Maxed HSA contributions for the year',
    xpValue: 60,
    icon: 'payments',
  ),
  Achievement(
    id: 'fin-ext-ext-brokerage-diversify',
    category: AchievementCategory.finance,
    title: 'Diversified Portfolio',
    description: 'Built a diversified brokerage portfolio',
    xpValue: 75,
    icon: 'payments',
  ),
  Achievement(
    id: 'fin-ext-ext-crypto-cold',
    category: AchievementCategory.finance,
    title: 'Cold Storage',
    description: 'Moved long-term holdings to cold storage',
    xpValue: 90,
    icon: 'payments',
  ),
  Achievement(
    id: 'fin-ext-ext-side-hustle-llc',
    category: AchievementCategory.finance,
    title: 'Side LLC',
    description: 'Registered an LLC for side work',
    xpValue: 105,
    icon: 'payments',
  ),
  Achievement(
    id: 'fin-ext-ext-invoice-system',
    category: AchievementCategory.finance,
    title: 'Invoice System',
    description: 'Ran invoicing for freelance income',
    xpValue: 120,
    icon: 'payments',
  ),
  Achievement(
    id: 'fin-ext-ext-credit-freeze',
    category: AchievementCategory.finance,
    title: 'Credit Freeze',
    description: 'Set up credit freezes proactively',
    xpValue: 135,
    icon: 'payments',
  ),
  Achievement(
    id: 'fin-ext-ext-subscription-audit',
    category: AchievementCategory.finance,
    title: 'Subscription Audit',
    description: 'Cut unused subscriptions for 6 months',
    xpValue: 150,
    icon: 'payments',
  ),
  Achievement(
    id: 'fin-ext-ext-co-op-member',
    category: AchievementCategory.finance,
    title: 'Co-op Member',
    description: 'Joined a credit union or co-op bank',
    xpValue: 165,
    icon: 'payments',
  ),
  Achievement(
    id: 'fin-ext-ext-tax-loss',
    category: AchievementCategory.finance,
    title: 'Tax-Loss Harvest',
    description: 'Executed tax-loss harvesting thoughtfully',
    xpValue: 180,
    icon: 'payments',
  ),
  Achievement(
    id: 'fin-ext-ext-kids-529',
    category: AchievementCategory.finance,
    title: '529 Started',
    description: 'Opened education savings for a child',
    xpValue: 195,
    icon: 'payments',
  ),
  Achievement(
    id: 'com-ext-ext-coat-drive',
    category: AchievementCategory.community,
    title: 'Coat Drive',
    description: 'Ran a winter coat drive',
    xpValue: 40,
    icon: 'forest',
  ),
  Achievement(
    id: 'com-ext-ext-soup-kitchen',
    category: AchievementCategory.community,
    title: 'Soup Kitchen',
    description: 'Served monthly at a soup kitchen',
    xpValue: 55,
    icon: 'forest',
  ),
  Achievement(
    id: 'com-ext-ext-transit-advocacy',
    category: AchievementCategory.community,
    title: 'Transit Advocate',
    description: 'Advocated for local transit improvements',
    xpValue: 70,
    icon: 'forest',
  ),
  Achievement(
    id: 'com-ext-ext-voter-reg',
    category: AchievementCategory.community,
    title: 'Voter Registration',
    description: 'Registered voters at an event',
    xpValue: 85,
    icon: 'forest',
  ),
  Achievement(
    id: 'com-ext-ext-skill-share',
    category: AchievementCategory.community,
    title: 'Skill Share',
    description: 'Hosted a free community skill share',
    xpValue: 100,
    icon: 'forest',
  ),
  Achievement(
    id: 'com-ext-ext-tool-library',
    category: AchievementCategory.community,
    title: 'Tool Library',
    description: 'Contributed to a community tool library',
    xpValue: 115,
    icon: 'forest',
  ),
  Achievement(
    id: 'com-ext-ext-stream-cleanup',
    category: AchievementCategory.community,
    title: 'Stream Cleanup',
    description: 'Cleaned a local waterway',
    xpValue: 130,
    icon: 'forest',
  ),
  Achievement(
    id: 'com-ext-ext-senior-tech',
    category: AchievementCategory.community,
    title: 'Senior Tech Help',
    description: 'Taught seniors basic tech monthly',
    xpValue: 145,
    icon: 'forest',
  ),
  Achievement(
    id: 'com-ext-ext-refugee-welcome',
    category: AchievementCategory.community,
    title: 'Welcome Team',
    description: 'Welcomed refugees or newcomers',
    xpValue: 160,
    icon: 'forest',
  ),
  Achievement(
    id: 'com-ext-ext-community-fridge',
    category: AchievementCategory.community,
    title: 'Community Fridge',
    description: 'Stocked a community fridge regularly',
    xpValue: 175,
    icon: 'forest',
  ),
  Achievement(
    id: 'fun-ext-ext-spoiler-sent',
    category: AchievementCategory.funny,
    title: 'Spoiler Sent',
    description: 'Accidentally spoiled a show',
    xpValue: 20,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-voicemail-long',
    category: AchievementCategory.funny,
    title: 'Long Voicemail',
    description: 'Left a voicemail over two minutes',
    xpValue: 28,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-microwave-fish',
    category: AchievementCategory.funny,
    title: 'Office Fish',
    description: 'Microwaved fish at work',
    xpValue: 36,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-caught-lying',
    category: AchievementCategory.funny,
    title: 'Caught Lyric',
    description: 'Sang wrong lyrics confidently',
    xpValue: 44,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-locked-out',
    category: AchievementCategory.funny,
    title: 'Locked Out',
    description: 'Locked yourself out in pajamas',
    xpValue: 52,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-wrong-door',
    category: AchievementCategory.funny,
    title: 'Wrong Door',
    description: 'Opened the wrong Uber door',
    xpValue: 60,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-food-delivery-wrong',
    category: AchievementCategory.funny,
    title: 'Wrong Order Eater',
    description: 'Ate someone else\'s delivery once',
    xpValue: 68,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-haircut-regret',
    category: AchievementCategory.funny,
    title: 'Haircut Regret',
    description: 'Immediately regretted a haircut',
    xpValue: 76,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-screenshot-fail',
    category: AchievementCategory.funny,
    title: 'Screenshot Fail',
    description: 'Screenshot included embarrassing UI',
    xpValue: 84,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-birthday-forgot',
    category: AchievementCategory.funny,
    title: 'Birthday Forgot',
    description: 'Forgot a close friend\'s birthday once',
    xpValue: 92,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-dad-joke',
    category: AchievementCategory.funny,
    title: 'Dad Joke Deployed',
    description: 'Deployed a peak dad joke',
    xpValue: 100,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-ghosted-by-mistake',
    category: AchievementCategory.funny,
    title: 'Ghosted by Mistake',
    description: 'Left someone on read for a week accidentally',
    xpValue: 108,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-printer-war',
    category: AchievementCategory.funny,
    title: 'Printer War',
    description: 'Lost a battle with office printer',
    xpValue: 116,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-emoji-overuse',
    category: AchievementCategory.funny,
    title: 'Emoji Overuse',
    description: 'Sent a paragraph of emojis',
    xpValue: 124,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'fun-ext-ext-narrator-voice',
    category: AchievementCategory.funny,
    title: 'Narrator Voice',
    description: 'Narrated your own life out loud',
    xpValue: 132,
    isFunny: true,
    icon: 'theater_comedy',
  ),
  Achievement(
    id: 'crt-ext-ext-zine',
    category: AchievementCategory.creative,
    title: 'Zine Published',
    description: 'Published a zine',
    xpValue: 40,
    icon: 'lyrics',
  ),
  Achievement(
    id: 'crt-ext-ext-comic-strip',
    category: AchievementCategory.creative,
    title: 'Comic Strip',
    description: 'Ran a comic strip for 30 days',
    xpValue: 55,
    icon: 'lyrics',
  ),
  Achievement(
    id: 'crt-ext-ext-dj-set',
    category: AchievementCategory.creative,
    title: 'DJ Set',
    description: 'Performed a live DJ set',
    xpValue: 70,
    icon: 'lyrics',
  ),
  Achievement(
    id: 'crt-ext-ext-choreography',
    category: AchievementCategory.creative,
    title: 'Choreography',
    description: 'Choreographed a performed piece',
    xpValue: 85,
    icon: 'lyrics',
  ),
  Achievement(
    id: 'crt-ext-ext-pottery-show',
    category: AchievementCategory.creative,
    title: 'Pottery Show',
    description: 'Showed pottery in a group show',
    xpValue: 100,
    icon: 'lyrics',
  ),
  Achievement(
    id: 'crt-ext-ext-ink-commission',
    category: AchievementCategory.creative,
    title: 'Ink Commission',
    description: 'Completed tattoo or ink commissions',
    xpValue: 115,
    icon: 'lyrics',
  ),
  Achievement(
    id: 'crt-ext-ext-voice-acting',
    category: AchievementCategory.creative,
    title: 'Voice Acting',
    description: 'Credited voice acting work',
    xpValue: 130,
    icon: 'lyrics',
  ),
  Achievement(
    id: 'crt-ext-ext-ux-case-study',
    category: AchievementCategory.creative,
    title: 'UX Case Study',
    description: 'Published a UX case study',
    xpValue: 145,
    icon: 'lyrics',
  ),
  Achievement(
    id: 'crt-ext-ext-brand-kit',
    category: AchievementCategory.creative,
    title: 'Brand Kit',
    description: 'Shipped a brand kit for a client',
    xpValue: 160,
    icon: 'lyrics',
  ),
  Achievement(
    id: 'crt-ext-ext-livestream-regular',
    category: AchievementCategory.creative,
    title: 'Livestream Regular',
    description: 'Streamed weekly for three months',
    xpValue: 175,
    icon: 'lyrics',
  ),
  Achievement(
    id: 'life-ext-ext-first-solo-cook',
    category: AchievementCategory.life,
    title: 'First Solo Feast',
    description: 'Cooked a full meal solo start to finish',
    xpValue: 40,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-plant-two',
    category: AchievementCategory.life,
    title: 'Second Plant',
    description: 'Kept two plants alive one year',
    xpValue: 55,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-vinyl-start',
    category: AchievementCategory.life,
    title: 'Vinyl Collector',
    description: 'Started a vinyl collection',
    xpValue: 70,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-board-game-night',
    category: AchievementCategory.life,
    title: 'Game Night Host',
    description: 'Hosted monthly board game nights',
    xpValue: 85,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-road-bike',
    category: AchievementCategory.life,
    title: 'Road Bike Commute',
    description: 'Commuted by road bike a season',
    xpValue: 100,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-stargazing',
    category: AchievementCategory.life,
    title: 'Stargazing Night',
    description: 'Stargazed away from city lights',
    xpValue: 115,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-aurora',
    category: AchievementCategory.life,
    title: 'Aurora Chaser',
    description: 'Saw aurora or rare sky event',
    xpValue: 130,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-comic-con',
    category: AchievementCategory.life,
    title: 'Fan Convention',
    description: 'Attended a fan convention',
    xpValue: 145,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-volunteer-day',
    category: AchievementCategory.life,
    title: 'Volunteer Day Off',
    description: 'Took PTO to volunteer',
    xpValue: 160,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-no-alarm-week',
    category: AchievementCategory.life,
    title: 'No Alarm Week',
    description: 'Woke without alarm for seven days',
    xpValue: 175,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-handwritten-cards',
    category: AchievementCategory.life,
    title: 'Card Stash',
    description: 'Kept blank cards to mail friends',
    xpValue: 190,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-closet-capsule',
    category: AchievementCategory.life,
    title: 'Capsule Wardrobe',
    description: 'Ran a capsule wardrobe season',
    xpValue: 205,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-balcony-garden',
    category: AchievementCategory.life,
    title: 'Balcony Garden',
    description: 'Grew food on a balcony',
    xpValue: 220,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-neighbor-help',
    category: AchievementCategory.life,
    title: 'Neighbor Help',
    description: 'Helped a neighbor in an emergency',
    xpValue: 235,
    icon: 'coffee',
  ),
  Achievement(
    id: 'life-ext-ext-new-hobby-year',
    category: AchievementCategory.life,
    title: 'New Hobby Year',
    description: 'Picked up and kept a hobby twelve months',
    xpValue: 250,
    icon: 'coffee',
  ),
];
