// GENERATED by scripts/sync_app_version.sh — do not edit by hand.
// Source: pubspec.yaml version line.

/// Semantic version (no build number).
const String kAppVersionName = '1.1.0-beta.2';

/// Android versionCode / iOS CFBundleVersion.
const int kAppBuildNumber = 6;

/// Human-readable label for Settings and release manifests.
const String kAppVersionLabel = '1.1.0-beta.2+6';

/// Release APK filename segment: vertiege-{name}+{build}-arm64-release.apk
String get kReleaseApkBasename =>
    'vertiege-1.1.0-beta.2+6-arm64-release.apk';
