#!/usr/bin/env bash
# Sync lib/config/build_info.dart from pubspec.yaml (single source of truth).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PUBSPEC="$ROOT/pubspec.yaml"
OUT="$ROOT/lib/config/build_info.dart"

line=$(grep -E '^version:' "$PUBSPEC" | head -1)
# version: 1.1.0-beta.2+6
raw="${line#version: }"
raw="${raw// /}"

name="${raw%%+*}"
build="${raw#*+}"
if [[ -z "$name" || -z "$build" || "$name" == "$raw" ]]; then
  echo "Invalid pubspec version (expected name+build): $line" >&2
  exit 1
fi

cat > "$OUT" <<EOF
// GENERATED by scripts/sync_app_version.sh — do not edit by hand.
// Source: pubspec.yaml version line.

/// Semantic version (no build number).
const String kAppVersionName = '$name';

/// Android versionCode / iOS CFBundleVersion.
const int kAppBuildNumber = $build;

/// Human-readable label for Settings and release manifests.
const String kAppVersionLabel = '${name}+${build}';

/// Release APK filename segment: vertiege-{name}+{build}-arm64-release.apk
String get kReleaseApkBasename =>
    'vertiege-${name}+${build}-arm64-release.apk';
EOF

echo "Synced $OUT ← $name+$build"
